### ISSUE TITLE
There's no @DataBoundConstructor on any constructor

### ISSUE THREAD

**Issue by bwagner5** [awslabs/aws-codepipeline-plugin-for-jenkins#11]
When trying to configure a job with CodePipeline as the SCM, I'm getting:

```
Caused by: org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of class com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelineSCM
```

I'm using Jenkins 2.9 with a free-style build.

**Comment by biagic** [comment]
Thanks for bringing this to our attention, what version of the CodePipeline plugin are you using?

**Comment by biagic** [comment]
We've identified the problem and are working on a fix. We will post an update to this thread once the fix is rolled out. Thanks for bringing this to our attention.

**Comment by pahud** [comment]
I am also having this issue on Jenkins 2.11 with plugin version 0.14.

**Comment by biagic** [comment]
We just released version 0.15 which should address this issue (it might take a few hours for it to be available from Jenkins' update site).

Can you give it a try, and let us know if this fixes the issue for you?

**Comment by pahud** [comment]
Hello, it works on my latest Jenkins 2.12.

Thanks!!

**Comment by biagic** [comment]
Great, I'll go ahead and close the issue, feel free to re-open it if needed.
