### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by oradwell** [awslabs/aws-codepipeline-plugin-for-jenkins#12]
The plugin creates a temporary file in `/tmp` directory before uploading it as an artifact. These files are not deleted unless the system is rebooted. As expected we don't ever reboot our CI server.

I think plugin should delete the compressed file after upload is complete.

```
+ mv archive.tar.gz build/
[AWS CodePipeline Plugin] Publishing artifacts
[AWS CodePipeline Plugin] Compressing Directory '/var/lib/jenkins/jobs/job-1/workspace/build' as a 'Zip' archive
[AWS CodePipeline Plugin] Uploading Artifact: {Name: MyAppBuild,Location: {Type: S3,S3Location: {BucketName: codepipeline-us-east-1-xxxxxxx,ObjectKey: job-1/MyAppBuild/3PifRb1}}}, file: /tmp/job-1-xxxxxxx.zip
[AWS CodePipeline Plugin] Upload Successful
[AWS CodePipeline Plugin] Build Succeeded. PutJobSuccessResult
```

`/tmp/job-1-xxxxxxx.zip` does not get deleted.

**Comment by biagic** [comment]
Thanks for bringing this to our attention Oliver, I agree, the plugin should delete these files after they've been uploaded.

Would you expect the plugin to keep the files around if the upload fails?

As a possible workaround until we make that change, you could create the compressed archive as part of your build, and point the publisher's output location to that file (a relative path from the root of your workspace).

If the location points to a normal file, not a directory, no zip file will be created in `/tmp`, the file will be uploaded as-is.

**Comment by oradwell** [comment]
I wouldn't want the file to stay even when the upload fails.

Thanks for the workaround! I will try that.
