### ISSUE TITLE
Jenkins Remoting not supported

### ISSUE THREAD

**Issue by mattmcclean** [awslabs/aws-codepipeline-plugin-for-jenkins#2]
According to the Jenkins docs, the SCM module should be designed to handle distributed builds (see: https://wiki.jenkins-ci.org/display/JENKINS/Remoting). I tried to run it with a Jenkins Slave but the source Zip file was not found so the build failed.

In the class **AWSCodePipelineSCM.java**, and in the method **checkout()** it should perform the S3 download and extraction in either a **Callable** class and supply it to the FilePath.act(Callable) method or via a command line in the **Launcher** class.

**Comment by schmittthomas** [comment]
Thank you for bringing this to our attention. We are already working on a fix.

**Comment by schmittthomas** [comment]
We added Jenkins Remoting Support in the latest commit 1a9be5e. Closing the issue. If you have any problems, feel free to reopen it.
