### ISSUE TITLE
Region EU-CENTRAL-1 is missing

### ISSUE THREAD

**Issue by davesade** [awslabs/aws-codepipeline-plugin-for-jenkins#20]
Hello,
quite recently we got CodePipeline in new region of eu-central-1. Could we have this implemented in the menu of your plugin, please?

**Comment by belltimo** [comment]
Hi David, thanks for taking the time to submit this pull request!

Support for eu-central-1 was added in this commit: f0ed321

If you update your plugin version to 0.22 you should now see it.
