### ISSUE TITLE
Increase max project name

### ISSUE THREAD

**Issue by okeydoke** [awslabs/aws-codepipeline-plugin-for-jenkins#22]
Currently the max project name is only 20 chars. This seems arbitrarily small and silently fails. Can you please increase the max limit to something higher. 100 maybe? Also while there update some of the other Max values?

https://github.com/awslabs/aws-codepipeline-plugin-for-jenkins/blob/master/src/main/java/com/amazonaws/codepipeline/jenkinsplugin/Validation.java#L29

**Comment by rajput-jitendra** [comment]
This has just been increased to 50. Does that suffice your use case?

**Comment by okeydoke** [comment]
Yeah probably helps. I dunno if there's a way to display an error message related to that limit if you exceed it so it's easier to know what is going on?

Thanks

**Comment by galmeida** [comment]
We currently do have a message stating the project name is invalid in jenkins.err log, next plugin release will improve message phrasing.

**Comment by galmeida** [comment]
next release will be available in a few hours, validation error messages have been [improved](https://github.com/awslabs/aws-codepipeline-plugin-for-jenkins/commit/82bb2917e1d66ec1f6a294ee9eb98f49aad59c90)

**Comment by okeydoke** [comment]
Thanks!
