### ISSUE TITLE
The number of output artifacts do not match

### ISSUE THREAD

**Issue by samd2** [awslabs/aws-codepipeline-plugin-for-jenkins#33]
Just a quick bug report, which can be closed if it's erroneous.

Attempted to use CodePipeline Publisher plugin. Left Output Locations, Output Location, Artifact Name - blank.  Empty.  
Ran Pipeline.
Error: "Failed to upload output artifact(s): The number of output artifacts in the Jenkins project and in the pipeline action do not match. Configure the output locations of your Jenkins project to match the pipeline action's output artifacts. Number of output locations in Jenkins project: 0, number of output artifacts in the pipeline action: 1"

Changed Location to /  , instead of blank.
Then it worked.

Possible re-confirmation of the issue?   June 18, 2018,  #jenkins IRC logs:

[20:16:18] <niche> Getting this error on Jenkins with AWS CodePipeLine any thoughts? "Failed to upload output artifact(s): The number of output artifacts in the Jenkins project and in the pipeline action do not match. Configure the output locations of your Jenkins project to match the pipeline action's output artifacts. Number of output locations in Jenkins project: 0, number of output artifacts in the pipeline action: 1"

**Comment by samd2** [comment]
Well, it is working now. The most likely explanation, although I really believed that I had set this - is the difference between the plugin with no output locations configured, compared to an empty output location configured. And, rebooted the server.  If anyone ever gets the same error, please comment in the thread. Closing for now.

**Comment by GMKBabu** [comment]
The number of output artifacts in the Jenkins project and in the pipeline action do not match. Configure the output locations of your Jenkins project to match the pipeline action's output artifacts. Number of output locations in Jenkins project: 1, number of output artifacts in the pipeline action: 0 [Pipeline: windows-pipeline, stage: Build, action: build].

**Comment by shubham1061** [comment]
getting the same error
