### ISSUE TITLE
CodePipeline doesn't appear under Source Code Management

### ISSUE THREAD

**Issue by menant** [awslabs/aws-codepipeline-plugin-for-jenkins#5]
Hi,

It's currently impossible to complete the steps "Step 1: Set Up Prerequisites" from the documentation (http://docs.aws.amazon.com/codepipeline/latest/userguide/getting-started-4.html#getting-started-4-prereqs) as the last commit seems to have broken the ability to see the entry "AWS CodePipeline" under "Source Code Management" when configuring a project.
This plugin shows as version 0.4 in Jenkins.

I reverted back to the previous commit (from Jul 23, 2015) and it works.
That plugin shows as version 0.2 in Jenkins.

I hope this helps,
Seb

**Comment by biagic** [comment]
Hi Seb,

Is your Jenkins installation using Java 7? The latest version of the plugin now requires Java 8 (Java 7 reached EOL in April 2015).

You should be able to confirm this is the problem by going to `Manage Jenkins` -> `System Log` -> `All Jenkins Logs`. You should see a major.minor version error in the logs:

```
Failed to scout com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelinePublisher$DescriptorImpl
java.lang.InstantiationException: java.lang.UnsupportedClassVersionError: com/amazonaws/codepipeline/jenkinsplugin/AWSCodePipelinePublisher$DescriptorImpl : Unsupported major.minor version 52.0
```

Upgrading to a Java 8 JVM should do the trick. If it's not a major.minor version problem, can you post the system log?

Thank you

**Comment by biagic** [comment]
Seb,

We decided to keep supporting Java 7 for backwards compatibility. Can you try the latest version, 0.5, and let us know if this fixes your problem?

**Comment by menant** [comment]
I confirm that the plugin now works with the stock Amazon Linux AMI release 2015.03 without any modifications.

Thanks!
